Use shop;
Select* from customer Limit 5;
-- What is the total revenue generated by male vs. female customers? 
Select gender, sum(purchase_amount) as Revenue from customer 
group by gender;

-- What customer used a discount but still spent more that the average purchase amount?
Select customer_id, purchase_amount from customer where discount_applied = 'Yes' and purchase_amount >= 
(Select avg(purchase_amount) from customer);

-- Which are the top 5 products with the highest average review rating?
Select item_purchased, Round(Avg(review_rating), 2) as "Average Product Rating" from customer group by item_purchased order by avg(review_rating) desc Limit 5;

-- Compare the average purchase amount between standard and express shipping
Select shipping_type, round(avg(purchase_amount), 2) from customer where shipping_type in ('standard', 'express') group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?
Select subscription_status, count(customer_id) as "Total_Customers", round(avg(purchase_amount), 2) as "Average_Spend", 
round(sum(purchase_amount),2) as "Total_Revenue" from customer group by subscription_status 
order by Total_Revenue, Average_Spend desc;

-- Which 5 products have the highest % of purchases with discount applied?
Select item_purchased,round(sum(Case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100, 2)  as discount_rate from customer group by item_purchased order by discount_rate desc Limit 5;

-- Segment customers into new, returning and loyal based on their
-- total number of previous purchases, and show the count of each segment
With customer_type as (
select customer_id, previous_purchases,
Case 
	When previous_purchases = 1 Then 'New'
    When previous_purchases Between 2 AND 10 Then 'Returning'
    Else 'Loyal'
    End As customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- What are the 3 top most purchased products within each category?
With item_counts as (
Select category, item_purchased, Count(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders from item_counts
where item_rank <= 3;


-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status, count(customer_id) as repeat_buyers
from customer where previous_purchases > 5 group by subscription_status;

-- What is the revenue contribution of each age group;
Select age_group, sum(purchase_amount) as Total_Revenue from customer group by age_group order by Total_Revenue desc;

-- Select * from customer Limit 5;


 

